### ISSUE TITLE
.

### ISSUE THREAD

**Issue by MDarvishi5124** [FDarkCoder/Escape-The-Obstacles#1]
سلام پارسا، پروژه (روی نسخۀ جدید گودوت) مشکل داره و درست اجرا نمیشه. نیاز به دیباگ داره.
بهتره برای نسخۀ جدیدش اصلاحات جدیدی رو از نظر گرافیکی انجام بدم، و خروجی درستی داشته باشیم.

**Comment by ParsaFaghani** [comment]
روی نسخه 3.6 یا 4.2?
اگه نسخه 4.x باشه بعضی از متد ها تغییر کرده و دوباره باید روی کد نویسی کار کنیم
اگه نیاز به کمک داری یه ایدی از تلگرام یا هرجایی بهتر بود بده بهتر بتونیم روی گیم کار کنیم

**Comment by MDarvishi5124** [comment]
من بیشتر قصد داشتم بازی رو از نظر گرافیکی بررسی کنم، و با حفظ همین شرایط صرفاً گرافیک منسجم‌تر و بهتری روی پروژه باشه. که با نسخۀ 3.6 هم راه می‌افته.
اما اگه حاضر هستی که یه خورده پروژه گسترش پیدا کنه، همین الان چند تا ایده تو ذهنم دارم.
تلگرامم: @MDarvishi5124

**Comment by ParsaFaghani** [comment]
توی تلگرام با این ایدی نیستی

و اگه ایده ای داری الان هردومون وقتشو داریم پیاده سازیش میکنیم
